[package]
name = "pdf_to_speech"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
lopdf = "0.35.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
urlencoding = "2.1.3"
serde = { version = "1.0", features = ["derive"] }